//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.NR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public long adminCommentId { get; set; }
        public long incidentId { get; set; }
        public long adminUserId { get; set; }
        public string adminUserName { get; set; }
        public string adminCommentText { get; set; }
        public System.DateTime adminCommentStamp { get; set; }
        public bool isDeleted { get; set; }
    }
}
