//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.NR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenter
    {
        public int costCenterId { get; set; }
        public string costCenterCode { get; set; }
        public string costCenterTitle { get; set; }
        public Nullable<int> costCenterTypeId { get; set; }
        public long directorId { get; set; }
        public long vpId { get; set; }
        public long crDirectorId { get; set; }
        public long crVpId { get; set; }
        public bool activeFlag { get; set; }
    }
}
