//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.NR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public long documentId { get; set; }
        public int fileTypeId { get; set; }
        public string documentFileName { get; set; }
        public string documentUrl { get; set; }
        public string documentTitle { get; set; }
        public string documentComments { get; set; }
        public long uploadedBy { get; set; }
        public System.DateTime uploadedStamp { get; set; }
        public bool isVoided { get; set; }
    }
}
