//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.NR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentType
    {
        public int incidentTypeId { get; set; }
        public int incidentReportTypeId { get; set; }
        public int incidentCategoryId { get; set; }
        public string incidentTypeText { get; set; }
        public bool needsInfo { get; set; }
        public string needsInfoLabel { get; set; }
        public string incidentTypeReportText { get; set; }
        public bool isActive { get; set; }
    }
}
