//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.NR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IncidentsEntities : DbContext
    {
        public IncidentsEntities()
            : base("name=IncidentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IncidentDetail> IncidentDetails { get; set; }
        public virtual DbSet<IncidentStaff> IncidentStaffs { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<ReportSign> ReportSigns { get; set; }
        public virtual DbSet<IncidentProgram> IncidentPrograms { get; set; }
        public virtual DbSet<IncidentType> IncidentTypes { get; set; }
        public virtual DbSet<NotifyParty> NotifyParties { get; set; }
        public virtual DbSet<ProgramNotifier> ProgramNotifiers { get; set; }
        public virtual DbSet<ReportSigType> ReportSigTypes { get; set; }
        public virtual DbSet<ReportStatu> ReportStatus { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<IncidentReport> IncidentReports { get; set; }
        public virtual DbSet<ApprovalStatu> ApprovalStatus { get; set; }
        public virtual DbSet<HarmRiskLevel> HarmRiskLevels { get; set; }
        public virtual DbSet<SpecialNotifier> SpecialNotifiers { get; set; }
        public virtual DbSet<IncidentAttachment> IncidentAttachments { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<HighRisk> HighRisks { get; set; }
        public virtual DbSet<ClientSystem> ClientSystems { get; set; }
    }
}
