//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.NR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentProgram
    {
        public int incidentProgramId { get; set; }
        public int costCenterId { get; set; }
        public string programTitle { get; set; }
        public bool isActive { get; set; }
        public int incidentReportTypeId { get; set; }
        public string reportingAgency { get; set; }
        public Nullable<long> programSuperId { get; set; }
        public string azSubUnit { get; set; }
        public long managerId { get; set; }
        public long directorId { get; set; }
    }
}
