//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.NR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyParty
    {
        public int notifyPartyId { get; set; }
        public int incidentReportTypeId { get; set; }
        public string notifyPartyText { get; set; }
        public bool needsInfo { get; set; }
        public string infoCaption { get; set; }
        public string infoPlaceholder { get; set; }
        public string validMessage { get; set; }
        public string contactDefault { get; set; }
        public string methodDefault { get; set; }
        public bool isActive { get; set; }
    }
}
