//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.NR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSign
    {
        public long reportSigId { get; set; }
        public long incidentId { get; set; }
        public string reportSigType { get; set; }
        public long incidentMedicalId { get; set; }
        public long reportSigUserId { get; set; }
        public string staffName { get; set; }
        public string staffTitle { get; set; }
        public int approvalStatusId { get; set; }
        public string approvalComments { get; set; }
        public Nullable<System.DateTime> reportSigStamp { get; set; }
        public string reportSigStation { get; set; }
        public System.DateTime reportSigCreated { get; set; }
    }
}
