//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.NR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialNotifier
    {
        public int notifierId { get; set; }
        public string notifierType { get; set; }
        public long notifierUserId { get; set; }
        public string notifierName { get; set; }
        public string notifierEmail { get; set; }
        public string notifierTitle { get; set; }
        public bool isActive { get; set; }
    }
}
