//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfs.Web.Incidents.NR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long userId { get; set; }
        public int employeeId { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string userName { get; set; }
        public string eMail { get; set; }
        public int securityLevelId { get; set; }
        public int costCenterId { get; set; }
        public int locationId { get; set; }
        public long supervisorId { get; set; }
        public string jobTitle { get; set; }
        public Nullable<System.DateTime> lastHireDate { get; set; }
        public System.DateTime accountCreated { get; set; }
        public string workPhone { get; set; }
        public string costCenter { get; set; }
        public string locationCode { get; set; }
        public bool glAccountAdminAccess { get; set; }
        public string flsaStatus { get; set; }
        public string employType { get; set; }
        public Nullable<double> abraHours { get; set; }
        public bool towerTraining { get; set; }
        public bool activeFlag { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public bool showBirthDate { get; set; }
        public Nullable<int> anasaziId { get; set; }
        public bool anasaziLive { get; set; }
        public bool anasaziTrain { get; set; }
        public bool anasaziTest { get; set; }
        public bool outlookSetup { get; set; }
        public bool isBenefitsEligible { get; set; }
        public double holidayHours { get; set; }
        public Nullable<long> timesheetApproverId { get; set; }
        public Nullable<bool> clinProductivity { get; set; }
        public Nullable<bool> essUser { get; set; }
        public Nullable<System.DateTime> termDate { get; set; }
        public Nullable<double> mobileMiles { get; set; }
    }
}
